### ISSUE TITLE
Can't set other colours through the Severity function. 

### ISSUE THREAD

**Issue by RIKIKU** [jgigler/Powershell.Slack#3]
Hi @jgigler ,
I feel that the Severity parameter for New-SlackRichNotification is a little restrictive. Using ValidateSet is nice in that it prevents a user from entering the wrong string value and that tab auto-complete can fill out the options for you, but as a trade-off it also prevents a user from using custom web colours which are allowed in the API. 

I personally don't have a use for this but I feel that since the API handles it, it should be available for use in Powershell as well.  I'm thinking that getting rid of the Validation set along with updating the help to explain the use of Good,Warning and Bad along with web colours, might be an option.  What are your thoughts?

**Comment by jgigler** [comment]
Sounds reasonable to support that feature. I think it would probably be
better from an implementation standpoint to have Severity with the validate
set of good, warning, bad be the default; and create a separate parameter
set to support a custom web color for the notification.

**Comment by RIKIKU** [comment]
Righto sounds good. I'll see if I can bang that out today.
